version: '2'
services:
  quiz-api-prod:
    build:
      context: ../../.
      dockerfile: ./docker/prod/Dockerfile
    volumes:
      - ../../.:/code/
      - /etc/localtime:/etc/localtime
    container_name: quiz-api-prod
    command: npm run start
    networks:
      - quiz-nextios-network
    environment:
      - NODE_ENV=production
      - APP_ENV=production
      - TERM=xterm-256color
    privileged: true
    links:
      - mongo-nextios-prod
    dns:
      - 8.8.8.8
    expose:
      - "8000"
      - "443"
    ports:
      - "8000:8080"
      - "443:443"
  mongo-nextios-prod:
    image: mongo:4.0
    container_name: mongo-nextios-prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: nextios
      MONGO_INITDB_ROOT_PASSWORD: q1w2e3r4
    volumes:
      - mongo-nextios:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - quiz-nextios-network
networks:
  quiz-nextios-network:
volumes:
  mongo-nextios:
